GET http://localhost:8000/docs HTTP/1.1

###

POST http://localhost:8000/user HTTP/1.1
Content-Type: application/json

{
  "email": "ibarra@gmail.com",
  "password": "18928928",
  "name": "Arthur",
  "photo_link": ""
}

###

POST http://localhost:8000/store HTTP/1.1
Content-Type: application/json

{
  "cnpj": "9696969696",
  "email": "funciona@porfavor.serio",
  "password": "1234",
  "name": "pelamor",
  "photo_link": "atane",
  "address": "rua vaifuncionarmesmo",
  "description": "puts"
}

###
GET http://localhost:8000/user_sales HTTP/1.1
Content-Type: application/json

{
  "email": "ibarra@gmail.com"
}